# Generated by Django 3.2.7 on 2021-12-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sapling', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=160)),
                ('images', models.ImageField(upload_to='', verbose_name='images')),
            ],
        ),
        migrations.DeleteModel(
            name='camp',
        ),
    ]
