# Generated by Django 3.2.7 on 2021-12-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0002_auto_20211226_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='images/'),
        ),
    ]
