# Generated by Django 3.2.7 on 2021-12-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0004_alter_imageupload_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
