# Generated by Django 3.2.7 on 2021-12-28 16:46

from django.db import migrations, models
import nss.models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0005_auto_20211228_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='awardsupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('images', models.ImageField(null=True, upload_to=nss.models.image_file_path)),
            ],
        ),
    ]
