# Generated by Django 3.2.7 on 2021-12-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0006_awardsupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=60)),
                ('youtube_link', models.URLField(unique=True)),
            ],
        ),
    ]
