# Generated by Django 3.2.7 on 2021-12-29 05:03

from django.db import migrations, models
import nss.models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0008_bdcupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='seminarupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=360)),
                ('images', models.ImageField(null=True, upload_to=nss.models.image_file_path)),
            ],
        ),
    ]
